{"name": "test_02_fio[sudo fio -filename=\\u6587\\u4ef6 -direct=1 -iodepth 1 -thread -rw=read -ioengine=psync -bs=1M -size=40G -group_reporting -name=mytest]", "status": "broken", "statusDetails": {"message": "ValueError: invalid literal for int() with base 10: '69.3'", "trace": "self = <Case.test_fio.TestIOzone object at 0x000001F8F55603B0>\ncmd = 'sudo fio -filename=文件 -direct=1 -iodepth 1 -thread -rw=read -ioengine=psync -bs=1M -size=40G -group_reporting -name=mytest'\n\n    @pytest.mark.description(\"fio硬盘性能测试: \"\n                             \"http://qa-zentao.mthreads.com:9000/testcase-view-8388-7.html?tid=xen4k1po\")\n    @pytest.mark.parametrize('cmd', [i[0] for i in data_fio])\n    def test_02_fio(self, cmd):\n        fio_rs = fp.send(cmd)\n>       final_rs = fp.assert_fio(fio_rs)\n\ntest_fio.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Utils.Base_init.BspTest object at 0x000001F8F5427B10>\nfio_rs = 'mytest: (g=0): rw=read, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=psync, iodepth=1\\n...1msec\\n\\nDisk stats (read/write):\\n  nvme0n1: ios=162363/53, merge=0/28, ticks=29211/18, in_queue=29236, util=99.40%\\n'\n\n    def assert_fio(self, fio_rs):\n        op = OperationData('fio.csv')\n        dict_list = dict(ChainMap(*op.get_data_dict()))\n        IOPS = re.search(r'IOPS=((\\d+.\\w))', fio_rs).group(1).strip()\n        run_time = re.search(r'(\\d{5})-(\\d{5}msec)', fio_rs).group(1).strip()\n        # print(dict_list['IOPS'], type(dict_list['IOPS']))\n        # print(dict_list['runtime'], type(dict_list['runtime']))\n        if float(IOPS) / float(dict_list['IOPS']) > 0.98 and int(run_time) / int(dict_list['runtime']) > 0.98:\n            logging.info(f'相较于x86对照数据：IOPS={dict_list['IOPS']}runtime={dict_list['runtime']}msec'\n                            f'测试数据：IOPS={IOPS} runtime={run_time}msec PASS')\n            return True\n        else:\n>           gap_result = float(int(IOPS) - int(dict_list['IOPS']) / int(IOPS))\nE           ValueError: invalid literal for int() with base 10: '69.3'\n\n..\\Utils\\Base_init.py:105: ValueError"}, "attachments": [{"name": "log", "source": "10ef6d55-eef4-428e-a480-72f8785cd191-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "cmd", "value": "'sudo fio -filename=文件 -direct=1 -iodepth 1 -thread -rw=read -ioengine=psync -bs=1M -size=40G -group_reporting -name=mytest'"}], "start": 1740473805156, "stop": 1740473851354, "uuid": "26de769a-142a-4945-8876-efab168c748c", "historyId": "d79d6d4e4e9f7ddaeced170337cea383", "testCaseId": "39baddf0d196c4f8caec87c0d2e6ef3d", "fullName": "Case.test_fio.TestIOzone#test_02_fio", "labels": [{"name": "tag", "value": "description('fio硬盘性能测试: http://qa-zentao.mthreads.com:9000/testcase-view-8388-7.html?tid=xen4k1po')"}, {"name": "parentSuite", "value": "Case"}, {"name": "suite", "value": "test_fio"}, {"name": "subSuite", "value": "TestIOzone"}, {"name": "host", "value": "Meiyi-EXT"}, {"name": "thread", "value": "20432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Case.test_fio"}]}